/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/native'
import { useFrame, Canvas } from '@react-three/fiber/native'
import path from './assets/iphone.glb';

export function Ipgone(props) {
  // try{
    const { scene } = useGLTF(path)
    // useFrame(() => (scene.rotation.y += 0.01,scene.rotation.x += 0.001, scene.rotation.z += 0.001 ))
    return (
      <primitive object={scene} />
      // <group {...props} dispose={null}>
      //   <group position={[0, -0.03, 0.11]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
      //     <mesh geometry={nodes.Mesh_0.geometry} material={materials['Mat.10']} />
      //     <mesh geometry={nodes.Mesh_0_1.geometry} material={materials['Mat.2']} />
      //     <mesh geometry={nodes.Mesh_0_2.geometry} material={materials['Material.001']} />
      //     <mesh geometry={nodes.Mesh_0_3.geometry} material={materials['Mat.1']} />
      //     <mesh geometry={nodes.Mesh_0_4.geometry} material={materials['Mat.6_2_1']} />
      //     <mesh geometry={nodes.Mesh_0_5.geometry} material={materials['Mat.6']} />
      //     <mesh geometry={nodes.Mesh_0_6.geometry} material={materials.Mat} />
      //     <mesh geometry={nodes.Mesh_0_7.geometry} material={materials['Material.011']} />
      //     <mesh geometry={nodes.Mesh_0_8.geometry} material={materials['Material.010']} />
      //     <mesh geometry={nodes.Mesh_0_9.geometry} material={materials['Mat.7']} />
      //     <mesh geometry={nodes.Mesh_0_10.geometry} material={materials['Mat.6_1']} />
      //     <mesh geometry={nodes.Mesh_0_11.geometry} material={materials['Mat.5']} />
      //     <mesh geometry={nodes.Mesh_0_12.geometry} material={materials['default']} />
      //     <mesh geometry={nodes.Mesh_0_13.geometry} material={materials['Mat.6_2']} />
      //     <mesh geometry={nodes.Mesh_0_14.geometry} material={materials['Mat.9']} />
      //     <mesh geometry={nodes.Mesh_0_15.geometry} material={materials['Mat.8']} />
      //     <mesh geometry={nodes.Mesh_0_16.geometry} material={materials['Mat.6_2.002']} />
      //     <mesh geometry={nodes.Mesh_0_17.geometry} material={materials['Mat.003']} />
      //   </group>
      //   <group position={[0, -0.03, 0.11]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
      //     <mesh geometry={nodes.Mesh_38.geometry} material={materials['Material.001']} />
      //     <mesh geometry={nodes.Mesh_38_1.geometry} material={materials['Mat.10']} />
      //   </group>
      //   <mesh geometry={nodes.Screen.geometry} material={materials['Mat.003']} position={[0, -0.03, 0.11]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      // </group>
    )
  // } catch(e) {
  //   console.log("Errorski: ",  e);
  // }
}

// useGLTF.preload(path)
